* Together with @vsande, redesign of the testing system such that now it has become much more     extensible and customizable. For each test, a handler script (which     can be written in an arbitrary scripting language, such as shell or perl)     has to be written. This handler script manages the low-level details     of the test, how it is called, the parameter-value combinations to be tested, etc.     We will write a note in the Wiki which describes how the system is designed and how it     can be extended to define new test sets.
  * Renamed test_dirsol_mm by test_serial_preconditioners_and_solvers and adapted test
    to the new testing system.

  * Added a new test, par_test_mlbddc_poisson_problem.f90, acompanying handler script, and input data,
    that allows to extensively test the mlbddc module. This test relies on FLAP for
    command-line parsing. It also tests some other subsystems of FEMPAR, such as
    parallel uniform refinement, parallel triangulation generation, integration of a
    problem with analytical solution, abstract Krylov methods, etc. A number
    of parameter-value combinations are currently being subject to testing.

   * Added prob.f90 as the header file of the Prob library. It was so far missing.

   * Pulled cdr.f90 and cdr_cg.90 from ocolomes's branch operator_structure_development. These
     files include a new subclass of type(discrete_integration_t), called type(cdr_nonlinear_t).
     Apart from implementing a non-linear cdr problem (which can be degenerated to linear by properly
     setting the corresponding data members) it has analytical solution support implemented.

   * Redefine par_fe_space_set_analytical_code as a TBP of type(par_fe_space_t) (to be consistent with
     type(fe_space_t)).

   * Added private at the header of lib_vtk_io_interface.f90. It was exporting all names (even the ones
     that were not relevant to clients of the module) and there was
     a collision among names declared in this module and others declared in matrix.f90.

   * Fixed the following linking errors reported by @principe. There were some errors in the code.

       ../../../lib/libfem.a(block_matrix.f90.o): In function `__block_matrix_names_MOD_block_matrix_apply_fun':
       /home/principe/Javier/Work/Prog/fempar/Sources/Serial/LinearAlgebra/block_matrix.f90:271: undefined reference to `matvec_'
       ../../../lib/libfem.a(block_matrix.f90.o): In function `__block_matrix_names_MOD_block_matrix_apply':
       /home/principe/Javier/Work/Prog/fempar/Sources/Serial/LinearAlgebra/block_matrix.f90:227: undefined reference to `matvec_'
       ../../../lib/libfem.a(block_matrix.f90.o): In function `__block_matrix_names_MOD_block_matrix_alloc_block':
       /home/principe/Javier/Work/Prog/fempar/Sources/Serial/LinearAlgebra/block_matrix.f90:132: undefined reference to `par_matrix_alloc_'